[project]
name = "nonstd"
version = "0.1.0"
description = "Useful python modules with sensible APIs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
