[project]
name = "nonstd"
version = "0.1.1"
description = "Useful python modules with sensible APIs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["pyright", "pytest", "ruff"]
